import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type UiLanguage = "ko" | "ja";
const ja: Record<string, string> = {
  "상담을 준비하고 있습니다": "相談を準備しています", "객실 접근 정보를 안전하게 확인하는 중입니다.": "客室のアクセス情報を安全に確認しています。", "실시간 상담 시작": "リアルタイム相談を開始", "상담은 최대 15분 동안 진행되며 텍스트 메시지만 지원합니다.": "相談は最大15分間で、テキストメッセージのみ対応しています。", "상담 언어": "相談言語", "상담 내용이 서비스 제공과 안전한 운영을 위해 저장될 수 있음을 확인했습니다. 비밀번호와 결제정보는 입력하지 않겠습니다.": "サービス提供と安全な運営のため相談内容が保存される場合があることを確認しました。パスワードや決済情報は入力しません。", "상담 준비 중…": "相談準備中…", "상담 시작": "相談開始", "상담을 시작할 수 없습니다": "相談を開始できません", "호텔 고객지원": "ホテルカスタマーサポート", "연결 중": "接続中", "연결됨": "接続済み", "연결 끊김": "切断", "재연결 중": "再接続中", "상담원 연결을 기다리고 있습니다. 연결되면 메시지를 보낼 수 있습니다.": "相談員への接続を待っています。接続後にメッセージを送信できます。", "상담원이 연결되었습니다. 개인정보나 결제 비밀번호는 전송하지 마세요.": "相談員に接続しました。個人情報や決済用パスワードは送信しないでください。", "상담이 종료되었습니다. 더 이상 메시지를 보낼 수 없습니다.": "相談は終了しました。これ以上メッセージを送信できません。", "잠시만 기다려 주세요.": "しばらくお待ちください。", "첫 메시지를 보내보세요.": "最初のメッセージを送ってみましょう。", "나": "自分", "상담원": "相談員", "남은 상담 시간": "相談残り時間", "종료": "終了", "메시지": "メッセージ", "메시지를 입력하세요": "メッセージを入力してください", "상담원 연결 또는 종료 상태를 확인하세요": "相談員への接続または終了状態を確認してください", "전송": "送信", "UI 언어": "表示言語"
};
interface Value { language: UiLanguage; setLanguage: (value: UiLanguage) => void; t: (text: string) => string; locale: string; }
const Context = createContext<Value | null>(null);
export function LanguageProvider({ children }: React.PropsWithChildren): React.JSX.Element { const [language,setLanguage]=useState<UiLanguage>(()=>localStorage.getItem("remoteplus-ui-language")==="ja"?"ja":"ko"); useEffect(()=>{localStorage.setItem("remoteplus-ui-language",language);document.documentElement.lang=language;},[language]); const value=useMemo(()=>({language,setLanguage,t:(text:string)=>language==="ja"?(ja[text]??text):text,locale:language==="ja"?"ja-JP":"ko-KR"}),[language]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useI18n(): Value { const value=useContext(Context); if(!value) throw new Error("LanguageProvider가 필요합니다."); return value; }
export function LanguageSwitcher(): React.JSX.Element { const {language,setLanguage,t}=useI18n(); return <label className="language-switcher"><span>{t("UI 언어")}</span><select aria-label={t("UI 언어")} value={language} onChange={(event)=>setLanguage(event.target.value as UiLanguage)}><option value="ko">한국어</option><option value="ja">日本語</option></select></label>; }
