FROM node:22-bookworm-slim AS builder
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm install --frozen-lockfile

ARG APP_PATH
ARG VITE_API_URL
ARG VITE_SOCKET_URL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SOCKET_URL=$VITE_SOCKET_URL
RUN pnpm --filter @hotel-chat/shared build && pnpm --filter "./${APP_PATH}" build

FROM nginx:1.27-alpine
COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf
ARG APP_PATH
COPY --from=builder /app/${APP_PATH}/dist /usr/share/nginx/html
EXPOSE 80
